version: '3'

services:
  proxy:
    image: nginx
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - 443:443
    environment:
      TZ: Asia/Tokyo
    restart: always

  acme-challenge:
    image: nginx
    volumes:
      - ./nginx/acme-challenge.conf:/etc/nginx/conf.d/default.conf
      - ./acme-challenge:/var/letsencrypt/www
    ports:
      - 80:80
    environment:
      TZ: Asia/Tokyo
    command: "/bin/sh -c 'while :; do sleep 36h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./acme-challenge:/var/letsencrypt/www
      - ./letsencrypt:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always

networks:
  default:
    external:
      name: nsfisis_dev_shared
