[locations]
contentDir = "/content"
destDir = "/public"
staticDir = "/static"

[rendering.html]
indentWidth = 2

[blog]
author = "nsfisis"
fqdn = "blog.nsfisis.dev"
siteName = "REPL: Rest-Eat-Program Loop"
siteCopyrightYear = 2021

[blog.tagLabels]
c = "C"
ci-cd = "CI/CD"
cohackpp = "紅白ぺぱ合戦"
composer = "Composer"
conference = "カンファレンス"
cpp = "C++"
cpp17 = "C++ 17"
game = "ゲーム"
gitlab = "GitLab"
go = "Go"
http = "HTTP"
isucon = "ISUCON"
macos = "macOS"
mncore-challenge = "MN-Core Challenge"
neovim = "Neovim"
note-to-self = "備忘録"
ouj = "放送大学"
perl = "Perl"
php = "PHP"
phpcon-nagoya = "PHP カンファレンス名古屋"
phpcon-odawara = "PHP カンファレンス小田原"
phpconfuk = "PHP カンファレンス福岡"
phpconkagawa = "PHP カンファレンス香川"
phpconokinawa = "PHP カンファレンス沖縄"
phperkaigi = "PHPerKaigi"
phpkansai = "PHP カンファレンス関西"
phpstudy-tokyo = "PHP 勉強会@東京"
piet = "Piet"
python = "Python"
python3 = "Python 3"
ruby = "Ruby"
ruby3 = "Ruby 3"
rubykaigi = "RubyKaigi"
rust = "Rust"
scala = "Scala"
scalamatsuri = "ScalaMatsuri"
trick = "TRICK"
vim = "Vim"
wasm = "WebAssembly"
wireguard = "WireGuard"
ya8 = "Ya8"
yaml = "YAML"
yapc = "YAPC"
zsh = "Zsh"
