module Nuldoc
  module DOM
    class HTMLBuilder < Builder
      def a(**attrs, &) = elem('a', **attrs, &)
      def article(**attrs, &) = elem('article', **attrs, &)
      def blockquote(**attrs, &) = elem('blockquote', **attrs, &)
      def body(**attrs, &) = elem('body', **attrs, &)
      def button(**attrs, &) = elem('button', **attrs, &)
      def canvas(**attrs, &) = elem('canvas', **attrs, &)
      def code(**attrs, &) = elem('code', **attrs, &)
      def del(**attrs, &) = elem('del', **attrs, &)
      def div(**attrs, &) = elem('div', **attrs, &)
      def em(**attrs, &) = elem('em', **attrs, &)
      def footer(**attrs, &) = elem('footer', **attrs, &)
      def h1(**attrs, &) = elem('h1', **attrs, &)
      def h2(**attrs, &) = elem('h2', **attrs, &)
      def h3(**attrs, &) = elem('h3', **attrs, &)
      def h4(**attrs, &) = elem('h4', **attrs, &)
      def h5(**attrs, &) = elem('h5', **attrs, &)
      def h6(**attrs, &) = elem('h6', **attrs, &)
      def head(**attrs, &) = elem('head', **attrs, &)
      def header(**attrs, &) = elem('header', **attrs, &)
      def hr(**attrs) = elem('hr', **attrs)
      def html(**attrs, &) = elem('html', **attrs, &)
      def img(**attrs) = elem('img', **attrs)
      def li(**attrs, &) = elem('li', **attrs, &)
      def link(**attrs) = elem('link', **attrs)
      def main(**attrs, &) = elem('main', **attrs, &)
      def meta(**attrs) = elem('meta', **attrs)
      def nav(**attrs, &) = elem('nav', **attrs, &)
      def ol(**attrs, &) = elem('ol', **attrs, &)
      def p(**attrs, &) = elem('p', **attrs, &)
      def script(**attrs, &) = elem('script', **attrs, &)
      def section(**attrs, &) = elem('section', **attrs, &)
      def span(**attrs, &) = elem('span', **attrs, &)
      def strong(**attrs, &) = elem('strong', **attrs, &)
      def table(**attrs, &) = elem('table', **attrs, &)
      def tbody(**attrs, &) = elem('tbody', **attrs, &)
      def thead(**attrs, &) = elem('thead', **attrs, &)
      def time(**attrs, &) = elem('time', **attrs, &)
      def title(**attrs, &) = elem('title', **attrs, &)
      def tr(**attrs, &) = elem('tr', **attrs, &)
      def ul(**attrs, &) = elem('ul', **attrs, &)
    end
  end
end
