[slide]
title = "list でない array の末尾を探す"
event = "PHP 勉強会@東京 第151 回"
talkType = "LT"
link = "/slides/2023-04-12/phpstudy-tokyo-151/slide.pdf"
tags = [
  "php",
  "phpstudy-tokyo",
]

[[slide.revisions]]
date = "2023-04-12"
remark = "登壇"
