[slide]
uuid = "6c377f3f-6f52-4074-b690-c79d02050562"
title = "PHP コードを隔離された環境で安全に動かす (on WebAssembly)"
event = "PHP 勉強会@東京 第157 回"
talkType = "LT"
link = "/slides/2023-10-25/phpstudy-tokyo-157/slide.pdf"
tags = [
  "php",
  "phpstudy-tokyo",
]

[[slide.revisions]]
date = "2023-10-25"
remark = "登壇"
