plugins:
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.4
  Enabled: true
  NewCops: enable

Metrics:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Documentation:
  Enabled: false
