[slide]
title = "PHP 3.0 の処理系のソースを読んでみる"
event = "PHP 勉強会@東京 第155 回"
talkType = "LT"
link = "/slides/2023-08-24/phpstudy-tokyo-155/slide.pdf"
tags = [
  "php",
  "phpstudy-tokyo",
]

[[slide.revisions]]
date = "2023-08-24"
remark = "登壇"
